GET http://localhost:3001/api/persons/
###


GET http://localhost:3001/api/persons/3
###
POST http://localhost:3001/api/persons/ HTTP/1.1
content-type: application/json

{
    "name": "Lolas",
    "number": "9879345024"
}

###
DELETE http://localhost:3001/api/persons/2



